SELECT B.TITLE, B.BOARD_ID, A.REPLY_ID, A.WRITER_ID, A.CONTENTS,
TO_CHAR(A.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_REPLY A
ON B.BOARD_ID = A.BOARD_ID
WHERE TO_CHAR(B.CREATED_DATE,'YYYY-MM') = '2022-10'
ORDER BY A.CREATED_DATE ASC, B.TITLE ASC